### ISSUE TITLE
Could you update the version of dependencies?

### ISSUE THREAD

**Issue by daabtech** [0rangeFox/Drogon-JWT-Filter-example#5]
The dependencies of this project have updated.Jwt-cpp have some Breaking Changes.Drogon and picojson and so on have updated too.Could you please update a new version that can  use the new version of the dependencies,thank you very much.

**Comment by daabtech** [comment]
您好，您的邮件我已经收到，我将在最短的时间内作出回复，谢谢，祝  万事如意！

**Comment by 0rangeFox** [comment]
Hey 👋, here is the new update as you requested, sorry for the delay but I didn't receive any notification about this "issue". And only today I decided to go back to review my projects where at the time I had not set up the notifications right and I put everything right now and I already receive notifications in any repository or whatever. Since it has been a long time I don't think this is relevant for you, but it is useful for new members and also to keep things as up to date as possible. Thanks for everything!

**Comment by daabtech** [comment]
This is very useful for me, thanks a lot!
